In [2]:
import numpy as np

w = 5

x = np.ones(10)
x = np.concatenate([x, np.ones(10) * 2])

x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2.])

In [3]:
kernel = np.ones(w) / w
kernel

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [6]:
np.convolve(x, kernel, mode="full")

array([0.2, 0.4, 0.6, 0.8, 1. , 1. , 1. , 1. , 1. , 1. , 1.2, 1.4, 1.6,
       1.8, 2. , 2. , 2. , 2. , 2. , 2. , 1.6, 1.2, 0.8, 0.4])

In [8]:
import os
import sys
import numpy as np
import matplotlib.pyplot as plt

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath("__file__"))) + "/src")

from ring_attractor.spiking import SpikeGenerator, SpikeGeneratorSimulator, SpikeProcessor

In [10]:
sp = SpikeProcessor(dt=1, bin_factor=1, smoothing_window=5) # 5 is the w

x_rev = x[::-1]
x_rev 

xm = np.stack([x, x_rev], axis=1)
xm

array([[1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.]])

In [11]:
sp.smooth_bins(xm)

ValueError: object too deep for desired array